export const FETCH_TRENDING_MOVIES_START = "FETCH_TRENDING_MOVIES_START";
export const FETCH_TRENDING_MOVIES_SUCCESS = "FETCH_TRENDING_MOVIES_SUCCESS";
export const FETCH_TRENDING_MOVIES_FAIL = "FETCH_TRENDING_MOVIES_FAIL";
//----------------------------------------------------------------------------------------
export const FETCH_MOVIES_UPCOMING_START = "FETCH_MOVIES_UPCOMING_START";
export const FETCH_MOVIES_UPCOMING_SUCCESS = "FETCH_MOVIES_UPCOMING_SUCCESS";
export const FETCH_MOVIES_UPCOMING_FAIL = "FETCH_MOVIES_UPCOMING_FAIL";

export const FETCH_MOVIES_NOW_PLAYING_START = "FETCH_MOVIES_NOW_PLAYING_START";
export const FETCH_MOVIES_NOW_PLAYING_SUCCESS = "FETCH_MOVIES_NOW_PLAYING_SUCCESS";
export const FETCH_MOVIES_NOW_PLAYING_FAIL = "FETCH_MOVIES_NOW_PLAYING_FAIL";

export const FETCH_MOVIES_POPULAR_START = "FETCH_MOVIES_POPULAR_START";
export const FETCH_MOVIES_POPULAR_SUCCESS = "FETCH_MOVIES_POPULAR_SUCCESS";
export const FETCH_MOVIES_POPULAR_FAIL = "FETCH_MOVIES_POPULAR_FAIL";

export const FETCH_MOVIES_TOP_RATED_START = "FETCH_MOVIES_TOP_RATED_START";
export const FETCH_MOVIES_TOP_RATED_SUCCESS = "FETCH_MOVIES_TOP_RATED_SUCCESS";
export const FETCH_MOVIES_TOP_RATED_FAIL = "FETCH_MOVIES_TOP_RATED_FAIL";
// ----------------------------------------------------------------------------------------
export const FETCH_TV_POPULAR_START = "FETCH_TV_POPULAR_START";
export const FETCH_TV_POPULAR_SUCCESS = "FETCH_TV_POPULAR_SUCCESS";
export const FETCH_TV_POPULAR_FAIL = "FETCH_TV_POPULAR_FAIL";

export const FETCH_TV_AIRING_TODAY_START = "FETCH_TV_AIRING_TODAY_START";
export const FETCH_TV_AIRING_TODAY_SUCCESS = "FETCH_TV_AIRING_TODAY_SUCCESS";
export const FETCH_TV_AIRING_TODAY_FAIL = "FETCH_TV_AIRING_TODAY_FAIL";

export const FETCH_TV_ON_THE_AIR_START = "FETCH_TV_ON_THE_AIR_START";
export const FETCH_TV_ON_THE_AIR_SUCCESS = "FETCH_TV_ON_THE_AIR_SUCCESS";
export const FETCH_TV_ON_THE_AIR_FAIL = "FETCH_TV_ON_THE_AIR_FAIL";

export const FETCH_TV_TOP_RATED_START = "FETCH_TV_TOP_RATED_START";
export const FETCH_TV_TOP_RATED_SUCCESS = "FETCH_TV_TOP_RATED_SUCCESS";
export const FETCH_TV_TOP_RATED_FAIL = "FETCH_TV_TOP_RATED_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_TV_GENRE_LIST_START = "FETCH_TV_GENRE_LIST_START";
export const FETCH_TV_GENRE_LIST_SUCCESS = "FETCH_TV_GENRE_LIST_SUCCESS";
export const FETCH_TV_GENRE_LIST_FAIL = "FETCH_TV_GENRE_LIST_FAIL";

export const FETCH_MOVIE_GENRE_LIST_START = "FETCH_MOVIE_GENRE_LIST_START";
export const FETCH_MOVIE_GENRE_LIST_SUCCESS = "FETCH_MOVIE_GENRE_LIST_SUCCESS";
export const FETCH_MOVIE_GENRE_LIST_FAIL = "FETCH_MOVIE_GENRE_LIST_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_TV_DISCOVER_START = "FETCH_TV_DISCOVER_START";
export const FETCH_TV_DISCOVER_SUCCESS = "FETCH_TV_DISCOVER_SUCCESS";
export const FETCH_TV_DISCOVER_FAIL = "FETCH_TV_DISCOVER_FAIL";

export const FETCH_MOVIE_DISCOVER_START = "FETCH_MOVIE_DISCOVER_START";
export const FETCH_MOVIE_DISCOVER_SUCCESS = "FETCH_MOVIE_DISCOVER_SUCCESS";
export const FETCH_MOVIE_DISCOVER_FAIL = "FETCH_MOVIE_DISCOVER_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_MOVIE_DETAILS_START = "FETCH_MOVIE_DETAILS_START";
export const FETCH_MOVIE_DETAILS_SUCCESS = "FETCH_MOVIE_DETAILS_SUCCESS";
export const FETCH_MOVIE_DETAILS_FAIL = "FETCH_MOVIE_DETAILS_FAIL";

export const FETCH_MOVIE_IMAGES_START = "FETCH_MOVIE_IMAGES_START";
export const FETCH_MOVIE_IMAGES_SUCCESS = "FETCH_MOVIE_IMAGES_SUCCESS";
export const FETCH_MOVIE_IMAGES_FAIL = "FETCH_MOVIE_IMAGES_FAIL";

export const FETCH_MOVIE_VIDEOS_START = "FETCH_MOVIE_VIDEOS_START";
export const FETCH_MOVIE_VIDEOS_SUCCESS = "FETCH_MOVIE_VIDEOS_SUCCESS";
export const FETCH_MOVIE_VIDEOS_FAIL = "FETCH_MOVIE_VIDEOS_FAIL";

export const FETCH_MOVIE_SIMILAR_START = "FETCH_MOVIE_SIMILAR_START";
export const FETCH_MOVIE_SIMILAR_SUCCESS = "FETCH_MOVIE_SIMILAR_SUCCESS";
export const FETCH_MOVIE_SIMILAR_FAIL = "FETCH_MOVIE_SIMILAR_FAIL";

export const FETCH_MOVIE_RECOMMENDATIONS_START = "FETCH_MOVIE_RECOMMENDATIONS_START";
export const FETCH_MOVIE_RECOMMENDATIONS_SUCCESS = "FETCH_MOVIE_RECOMMENDATIONS_SUCCESS";
export const FETCH_MOVIE_RECOMMENDATIONS_FAIL = "FETCH_MOVIE_RECOMMENDATIONS_FAIL";

export const FETCH_MOVIE_REVIEWS_START = "FETCH_MOVIE_REVIEWS_START";
export const FETCH_MOVIE_REVIEWS_SUCCESS = "FETCH_MOVIE_REVIEWS_SUCCESS";
export const FETCH_MOVIE_REVIEWS_FAIL = "FETCH_MOVIE_REVIEWS_FAIL";

export const FETCH_MOVIE_KEYWORDS_START = "FETCH_MOVIE_KEYWORDS_START";
export const FETCH_MOVIE_KEYWORDS_SUCCESS = "FETCH_MOVIE_KEYWORDS_SUCCESS";
export const FETCH_MOVIE_KEYWORDS_FAIL = "FETCH_MOVIE_KEYWORDS_FAIL";

export const FETCH_MOVIE_CREDITS_START = "FETCH_MOVIE_CREDITS_START";
export const FETCH_MOVIE_CREDITS_SUCCESS = "FETCH_MOVIE_CREDITS_SUCCESS";
export const FETCH_MOVIE_CREDITS_FAIL = "FETCH_MOVIE_CREDITS_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_TV_DETAILS_START = "FETCH_TV_DETAILS_START";
export const FETCH_TV_DETAILS_SUCCESS = "FETCH_TV_DETAILS_SUCCESS";
export const FETCH_TV_DETAILS_FAIL = "FETCH_TV_DETAILS_FAIL";

export const FETCH_TV_IMAGES_START = "FETCH_TV_IMAGES_START";
export const FETCH_TV_IMAGES_SUCCESS = "FETCH_TV_IMAGES_SUCCESS";
export const FETCH_TV_IMAGES_FAIL = "FETCH_TV_IMAGES_FAIL";

export const FETCH_TV_VIDEOS_START = "FETCH_TV_VIDEOS_START";
export const FETCH_TV_VIDEOS_SUCCESS = "FETCH_TV_VIDEOS_SUCCESS";
export const FETCH_TV_VIDEOS_FAIL = "FETCH_TV_VIDEOS_FAIL";

export const FETCH_TV_SIMILAR_START = "FETCH_TV_SIMILAR_START";
export const FETCH_TV_SIMILAR_SUCCESS = "FETCH_TV_SIMILAR_SUCCESS";
export const FETCH_TV_SIMILAR_FAIL = "FETCH_TV_SIMILAR_FAIL";

export const FETCH_TV_RECOMMENDATIONS_START = "FETCH_TV_RECOMMENDATIONS_START";
export const FETCH_TV_RECOMMENDATIONS_SUCCESS = "FETCH_TV_RECOMMENDATIONS_SUCCESS";
export const FETCH_TV_RECOMMENDATIONS_FAIL = "FETCH_TV_RECOMMENDATIONS_FAIL";

export const FETCH_TV_REVIEWS_START = "FETCH_TV_REVIEWS_START";
export const FETCH_TV_REVIEWS_SUCCESS = "FETCH_TV_REVIEWS_SUCCESS";
export const FETCH_TV_REVIEWS_FAIL = "FETCH_TV_REVIEWS_FAIL";

export const FETCH_TV_KEYWORDS_START = "FETCH_TV_KEYWORDS_START";
export const FETCH_TV_KEYWORDS_SUCCESS = "FETCH_TV_KEYWORDS_SUCCESS";
export const FETCH_TV_KEYWORDS_FAIL = "FETCH_TV_KEYWORDS_FAIL";

export const FETCH_TV_CREDITS_START = "FETCH_TV_CREDITS_START";
export const FETCH_TV_CREDITS_SUCCESS = "FETCH_TV_CREDITS_SUCCESS";
export const FETCH_TV_CREDITS_FAIL = "FETCH_TV_CREDITS_FAIL";
//------------------------------------------------------------------------------------------
export const FETCH_MOVIE_SEARCH_START = "FETCH_MOVIE_SEARCH_START";
export const FETCH_MOVIE_SEARCH_SUCCESS = "FETCH_MOVIE_SEARCH_SUCCESS";
export const FETCH_MOVIE_SEARCH_FAIL = "FETCH_MOVIE_SEARCH_FAIL";

export const FETCH_TV_SEARCH_START = "FETCH_TV_SEARCH_START";
export const FETCH_TV_SEARCH_SUCCESS = "FETCH_TV_SEARCH_SUCCESS";
export const FETCH_TV_SEARCH_FAIL = "FETCH_TV_SEARCH_FAIL";

export const TYPE_IS_SHOW = "TYPE_IS_SHOW"
export const TYPE_IS_MOVIE = "TYPE_IS_MOVIE"
//------------------------------------------------------------------------------------------
export const AUTH_SIGNUP_START = "AUTH_SIGNUP_START"
export const AUTH_SIGNUP_SUCCESS = "AUTH_SIGNUP_SUCCESS"
export const AUTH_SIGNUP_FAIL = "AUTH_SIGNUP_FAIL"

export const AUTH_LOGIN_START = "AUTH_LOGIN_START"
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS"
export const AUTH_LOGIN_FAIL = "AUTH_LOGIN_FAIL"

export const AUTH_VALID_START = "AUTH_VALID_START"
export const AUTH_VALID_SUCCESS = "AUTH_VALID_SUCCESS"
export const AUTH_VALID_FAIL = "AUTH_VALID_FAIL"

export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START"
export const AUTH_LOGOUT_SUCCESS = "AUTH_LOGOUT_SUCCESS"
export const AUTH_LOGOUT_FAIL = "AUTH_LOGOUT_FAIL"
//------------------------------------------------------------------------------------------
export const USER_DETAILS_START = "USER_DETAILS_START"
export const USER_DETAILS_SUCCESS = "USER_DETAILS_SUCCESS"
export const USER_DETAILS_FAIL = "USER_DETAILS_FAIL"

export const FETCH_FAVORITES_START = "FETCH_FAVORITES_START"
export const FETCH_FAVORITES_SUCCESS = "FETCH_FAVORITES_SUCCESS"
export const FETCH_FAVORITES_FAIL = "FETCH_FAVORITES_FAIL"

export const ADD_FAVORITES_START = "ADD_FAVORITES_START"
export const ADD_FAVORITES_SUCCESS = "ADD_FAVORITES_SUCCESS"
export const ADD_FAVORITES_FAIL = "ADD_FAVORITES_FAIL"

export const REMOVE_FAVORITES_START = "REMOVE_FAVORITES_START"
export const REMOVE_FAVORITES_SUCCESS = "REMOVE_FAVORITES_SUCCESS"
export const REMOVE_FAVORITES_FAIL = "REMOVE_FAVORITES_FAIL"